# NLP

In [2]:
#!pip install nltk
#!pip install clean-text

In [3]:
#import libraries
import pandas as pd
import numpy as np
import nltk 
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
import re
from cleantext import clean

In [4]:
para = '''— Tensor and Tensorflow: A powerful combo 💪
The Google Brain team developed an advanced AI framework named Tensorflow years back. After that, Google designed its own processing unit named Tensor Processing Unit or TPU to perform more efficiently with the Tensorflow. The invention of TPU was a revolution in AI that has significantly expedited the training of huge machine learning models with millions (or, billions) of parameters. Nevertheless, that technology could not be used in low-power devices such as smartphones in Edge AI. The entrance of Google into the AI chip manufacturing club for low-power devices can be the next revolution in this industry. Many companies such as FogHorn and BlinkAI are working in Edge AI using currently existing AI chips in the market. However, the efficacy that Google can create by the combination of TensorFlow and Tensor will be game-changing. Welcome to the club, Google!

— Tensor is an AI chip designed by AI! 😲
Isn’t that cool? The story is started from an article published in Nature titles “A graph placement methodology for fast chip design”. To design a processing chip, there is a crucial step referred to as “floor planning” where the engineering team must place a large number of components such that a series of physical requirements including power consumption and performance get satisfied. I don’t go further into its details as I am also not an expert in hardware engineering. However, when you have a large series of choices to make with a series of constraints AI can kick in. You may remember how the AlphaGo project defeated a professional human Go player. This is exactly the same. Tensor is the real outcome of this project that is a new milestone in the AI industry. Kudos, Google!

— Tensor helps us build ethical AI. 💡
This is a double-edged sword statement. Ethical AI has various aspects from data privacy to AI for all. Tensor helps many users have the opportunity to try the latest AI advancement while they have no concern about their privacy. Why? Because the AI engine is running on the chip, and no data is sent to the cloud for further computation. On the other hand, the more tightly Google binds AI software and hardware, the harder it will be for other companies to compete. I don’t want to see days that other companies can not even compete on performing AI inference, i.e., compete on using AI. We almost lost the game of model training to giant tech companies. It would be a nightmare if we lose the game on AI inference to them as well. That is why I believe “Tensor helps us build ethical AI” is a double-edged sword.'''
para

'— Tensor and Tensorflow: A powerful combo 💪\nThe Google Brain team developed an advanced AI framework named Tensorflow years back. After that, Google designed its own processing unit named Tensor Processing Unit or TPU to perform more efficiently with the Tensorflow. The invention of TPU was a revolution in AI that has significantly expedited the training of huge machine learning models with millions (or, billions) of parameters. Nevertheless, that technology could not be used in low-power devices such as smartphones in Edge AI. The entrance of Google into the AI chip manufacturing club for low-power devices can be the next revolution in this industry. Many companies such as FogHorn and BlinkAI are working in Edge AI using currently existing AI chips in the market. However, the efficacy that Google can create by the combination of TensorFlow and Tensor will be game-changing. Welcome to the club, Google!\n\n— Tensor is an AI chip designed by AI! 😲\nIsn’t that cool? The story is started from an article published in Nature titles “A graph placement methodology for fast chip design”. To design a processing chip, there is a crucial step referred to as “floor planning” where the engineering team must place a large number of components such that a series of physical requirements including power consumption and performance get satisfied. I don’t go further into its details as I am also not an expert in hardware engineering. However, when you have a large series of choices to make with a series of constraints AI can kick in. You may remember how the AlphaGo project defeated a professional human Go player. This is exactly the same. Tensor is the real outcome of this project that is a new milestone in the AI industry. Kudos, Google!\n\n— Tensor helps us build ethical AI. 💡\nThis is a double-edged sword statement. Ethical AI has various aspects from data privacy to AI for all. Tensor helps many users have the opportunity to try the latest AI advancement while they have no concern about their privacy. Why? Because the AI engine is running on the chip, and no data is sent to the cloud for further computation. On the other hand, the more tightly Google binds AI software and hardware, the harder it will be for other companies to compete. I don’t want to see days that other companies can not even compete on performing AI inference, i.e., compete on using AI. We almost lost the game of model training to giant tech companies. It would be a nightmare if we lose the game on AI inference to them as well. That is why I believe “Tensor helps us build ethical AI” is a double-edged sword.'

In [5]:
len(para)

2602

In [6]:
para[2]

'T'

# Removing Emojis

In [8]:
clean(para, no_emoji=True)

'-- tensor and tensorflow: a powerful combo\nthe google brain team developed an advanced ai framework named tensorflow years back. after that, google designed its own processing unit named tensor processing unit or tpu to perform more efficiently with the tensorflow. the invention of tpu was a revolution in ai that has significantly expedited the training of huge machine learning models with millions (or, billions) of parameters. nevertheless, that technology could not be used in low-power devices such as smartphones in edge ai. the entrance of google into the ai chip manufacturing club for low-power devices can be the next revolution in this industry. many companies such as foghorn and blinkai are working in edge ai using currently existing ai chips in the market. however, the efficacy that google can create by the combination of tensorflow and tensor will be game-changing. welcome to the club, google!\n-- tensor is an ai chip designed by ai!\nisn\'t that cool? the story is started from an article published in nature titles "a graph placement methodology for fast chip design". to design a processing chip, there is a crucial step referred to as "floor planning" where the engineering team must place a large number of components such that a series of physical requirements including power consumption and performance get satisfied. i don\'t go further into its details as i am also not an expert in hardware engineering. however, when you have a large series of choices to make with a series of constraints ai can kick in. you may remember how the alphago project defeated a professional human go player. this is exactly the same. tensor is the real outcome of this project that is a new milestone in the ai industry. kudos, google!\n-- tensor helps us build ethical ai.\nthis is a double-edged sword statement. ethical ai has various aspects from data privacy to ai for all. tensor helps many users have the opportunity to try the latest ai advancement while they have no concern about their privacy. why? because the ai engine is running on the chip, and no data is sent to the cloud for further computation. on the other hand, the more tightly google binds ai software and hardware, the harder it will be for other companies to compete. i don\'t want to see days that other companies can not even compete on performing ai inference, i.e., compete on using ai. we almost lost the game of model training to giant tech companies. it would be a nightmare if we lose the game on ai inference to them as well. that is why i believe "tensor helps us build ethical ai" is a double-edged sword.'

# Tokenization

In [10]:
para

'— Tensor and Tensorflow: A powerful combo 💪\nThe Google Brain team developed an advanced AI framework named Tensorflow years back. After that, Google designed its own processing unit named Tensor Processing Unit or TPU to perform more efficiently with the Tensorflow. The invention of TPU was a revolution in AI that has significantly expedited the training of huge machine learning models with millions (or, billions) of parameters. Nevertheless, that technology could not be used in low-power devices such as smartphones in Edge AI. The entrance of Google into the AI chip manufacturing club for low-power devices can be the next revolution in this industry. Many companies such as FogHorn and BlinkAI are working in Edge AI using currently existing AI chips in the market. However, the efficacy that Google can create by the combination of TensorFlow and Tensor will be game-changing. Welcome to the club, Google!\n\n— Tensor is an AI chip designed by AI! 😲\nIsn’t that cool? The story is started from an article published in Nature titles “A graph placement methodology for fast chip design”. To design a processing chip, there is a crucial step referred to as “floor planning” where the engineering team must place a large number of components such that a series of physical requirements including power consumption and performance get satisfied. I don’t go further into its details as I am also not an expert in hardware engineering. However, when you have a large series of choices to make with a series of constraints AI can kick in. You may remember how the AlphaGo project defeated a professional human Go player. This is exactly the same. Tensor is the real outcome of this project that is a new milestone in the AI industry. Kudos, Google!\n\n— Tensor helps us build ethical AI. 💡\nThis is a double-edged sword statement. Ethical AI has various aspects from data privacy to AI for all. Tensor helps many users have the opportunity to try the latest AI advancement while they have no concern about their privacy. Why? Because the AI engine is running on the chip, and no data is sent to the cloud for further computation. On the other hand, the more tightly Google binds AI software and hardware, the harder it will be for other companies to compete. I don’t want to see days that other companies can not even compete on performing AI inference, i.e., compete on using AI. We almost lost the game of model training to giant tech companies. It would be a nightmare if we lose the game on AI inference to them as well. That is why I believe “Tensor helps us build ethical AI” is a double-edged sword.'

In [11]:
#nltk.download('punkt')

In [12]:
from nltk.tokenize import word_tokenize

In [13]:
doc = 'This is NLP class'
# word_tokenize(doc)
doc.split(' ')

['This', 'is', 'NLP', 'class']

In [14]:
doc = 'This is NLP class'
word_tokenize(doc)
#doc.split(' ')

['This', 'is', 'NLP', 'class']

In [15]:
sent = sent_tokenize(para)
sent

['— Tensor and Tensorflow: A powerful combo 💪\nThe Google Brain team developed an advanced AI framework named Tensorflow years back.',
 'After that, Google designed its own processing unit named Tensor Processing Unit or TPU to perform more efficiently with the Tensorflow.',
 'The invention of TPU was a revolution in AI that has significantly expedited the training of huge machine learning models with millions (or, billions) of parameters.',
 'Nevertheless, that technology could not be used in low-power devices such as smartphones in Edge AI.',
 'The entrance of Google into the AI chip manufacturing club for low-power devices can be the next revolution in this industry.',
 'Many companies such as FogHorn and BlinkAI are working in Edge AI using currently existing AI chips in the market.',
 'However, the efficacy that Google can create by the combination of TensorFlow and Tensor will be game-changing.',
 'Welcome to the club, Google!',
 '— Tensor is an AI chip designed by AI!',
 '😲\nIsn’t that cool?',
 'The story is started from an article published in Nature titles “A graph placement methodology for fast chip design”.',
 'To design a processing chip, there is a crucial step referred to as “floor planning” where the engineering team must place a large number of components such that a series of physical requirements including power consumption and performance get satisfied.',
 'I don’t go further into its details as I am also not an expert in hardware engineering.',
 'However, when you have a large series of choices to make with a series of constraints AI can kick in.',
 'You may remember how the AlphaGo project defeated a professional human Go player.',
 'This is exactly the same.',
 'Tensor is the real outcome of this project that is a new milestone in the AI industry.',
 'Kudos, Google!',
 '— Tensor helps us build ethical AI.',
 '💡\nThis is a double-edged sword statement.',
 'Ethical AI has various aspects from data privacy to AI for all.',
 'Tensor helps many users have the opportunity to try the latest AI advancement while they have no concern about their privacy.',
 'Why?',
 'Because the AI engine is running on the chip, and no data is sent to the cloud for further computation.',
 'On the other hand, the more tightly Google binds AI software and hardware, the harder it will be for other companies to compete.',
 'I don’t want to see days that other companies can not even compete on performing AI inference, i.e., compete on using AI.',
 'We almost lost the game of model training to giant tech companies.',
 'It would be a nightmare if we lose the game on AI inference to them as well.',
 'That is why I believe “Tensor helps us build ethical AI” is a double-edged sword.']

In [16]:
len(sent)

29

In [17]:
sent[28]

'That is why I believe “Tensor helps us build ethical AI” is a double-edged sword.'

# Cleaning the data

In [19]:
range(len(sent))

range(0, 29)

In [20]:
corpus = []

for i in range(len(sent)):
    txt = re.sub('[^a-zA-Z]',' ', sent[i])
    txt = txt.lower()
    corpus.append(txt)

In [21]:
corpus

['  tensor and tensorflow  a powerful combo   the google brain team developed an advanced ai framework named tensorflow years back ',
 'after that  google designed its own processing unit named tensor processing unit or tpu to perform more efficiently with the tensorflow ',
 'the invention of tpu was a revolution in ai that has significantly expedited the training of huge machine learning models with millions  or  billions  of parameters ',
 'nevertheless  that technology could not be used in low power devices such as smartphones in edge ai ',
 'the entrance of google into the ai chip manufacturing club for low power devices can be the next revolution in this industry ',
 'many companies such as foghorn and blinkai are working in edge ai using currently existing ai chips in the market ',
 'however  the efficacy that google can create by the combination of tensorflow and tensor will be game changing ',
 'welcome to the club  google ',
 '  tensor is an ai chip designed by ai ',
 '  isn t that cool ',
 'the story is started from an article published in nature titles  a graph placement methodology for fast chip design  ',
 'to design a processing chip  there is a crucial step referred to as  floor planning  where the engineering team must place a large number of components such that a series of physical requirements including power consumption and performance get satisfied ',
 'i don t go further into its details as i am also not an expert in hardware engineering ',
 'however  when you have a large series of choices to make with a series of constraints ai can kick in ',
 'you may remember how the alphago project defeated a professional human go player ',
 'this is exactly the same ',
 'tensor is the real outcome of this project that is a new milestone in the ai industry ',
 'kudos  google ',
 '  tensor helps us build ethical ai ',
 '  this is a double edged sword statement ',
 'ethical ai has various aspects from data privacy to ai for all ',
 'tensor helps many users have the opportunity to try the latest ai advancement while they have no concern about their privacy ',
 'why ',
 'because the ai engine is running on the chip  and no data is sent to the cloud for further computation ',
 'on the other hand  the more tightly google binds ai software and hardware  the harder it will be for other companies to compete ',
 'i don t want to see days that other companies can not even compete on performing ai inference  i e   compete on using ai ',
 'we almost lost the game of model training to giant tech companies ',
 'it would be a nightmare if we lose the game on ai inference to them as well ',
 'that is why i believe  tensor helps us build ethical ai  is a double edged sword ']

# Stemming and stopwords removal

In [23]:
stemmer = PorterStemmer()

In [24]:
stemmer.stem('argued')

'argu'

In [25]:
stemmer.stem('historically')

'histor'

In [26]:
corpus

['  tensor and tensorflow  a powerful combo   the google brain team developed an advanced ai framework named tensorflow years back ',
 'after that  google designed its own processing unit named tensor processing unit or tpu to perform more efficiently with the tensorflow ',
 'the invention of tpu was a revolution in ai that has significantly expedited the training of huge machine learning models with millions  or  billions  of parameters ',
 'nevertheless  that technology could not be used in low power devices such as smartphones in edge ai ',
 'the entrance of google into the ai chip manufacturing club for low power devices can be the next revolution in this industry ',
 'many companies such as foghorn and blinkai are working in edge ai using currently existing ai chips in the market ',
 'however  the efficacy that google can create by the combination of tensorflow and tensor will be game changing ',
 'welcome to the club  google ',
 '  tensor is an ai chip designed by ai ',
 '  isn t that cool ',
 'the story is started from an article published in nature titles  a graph placement methodology for fast chip design  ',
 'to design a processing chip  there is a crucial step referred to as  floor planning  where the engineering team must place a large number of components such that a series of physical requirements including power consumption and performance get satisfied ',
 'i don t go further into its details as i am also not an expert in hardware engineering ',
 'however  when you have a large series of choices to make with a series of constraints ai can kick in ',
 'you may remember how the alphago project defeated a professional human go player ',
 'this is exactly the same ',
 'tensor is the real outcome of this project that is a new milestone in the ai industry ',
 'kudos  google ',
 '  tensor helps us build ethical ai ',
 '  this is a double edged sword statement ',
 'ethical ai has various aspects from data privacy to ai for all ',
 'tensor helps many users have the opportunity to try the latest ai advancement while they have no concern about their privacy ',
 'why ',
 'because the ai engine is running on the chip  and no data is sent to the cloud for further computation ',
 'on the other hand  the more tightly google binds ai software and hardware  the harder it will be for other companies to compete ',
 'i don t want to see days that other companies can not even compete on performing ai inference  i e   compete on using ai ',
 'we almost lost the game of model training to giant tech companies ',
 'it would be a nightmare if we lose the game on ai inference to them as well ',
 'that is why i believe  tensor helps us build ethical ai  is a double edged sword ']

In [27]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [28]:
stopwords.words('English')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [29]:
for i in corpus:
    print(i)

  tensor and tensorflow  a powerful combo   the google brain team developed an advanced ai framework named tensorflow years back
after that  google designed its own processing unit named tensor processing unit or tpu to perform more efficiently with the tensorflow
the invention of tpu was a revolution in ai that has significantly expedited the training of huge machine learning models with millions  or  billions  of parameters
nevertheless  that technology could not be used in low power devices such as smartphones in edge ai
the entrance of google into the ai chip manufacturing club for low power devices can be the next revolution in this industry
many companies such as foghorn and blinkai are working in edge ai using currently existing ai chips in the market
however  the efficacy that google can create by the combination of tensorflow and tensor will be game changing
welcome to the club  google
  tensor is an ai chip designed by ai
  isn t that cool
the story is started from an article published in nature titles  a graph placement methodology for fast chip design
to design a processing chip  there is a crucial step referred to as  floor planning  where the engineering team must place a large number of components such that a series of physical requirements including power consumption and performance get satisfied
i don t go further into its details as i am also not an expert in hardware engineering
however  when you have a large series of choices to make with a series of constraints ai can kick in
you may remember how the alphago project defeated a professional human go player
this is exactly the same
tensor is the real outcome of this project that is a new milestone in the ai industry
kudos  google
  tensor helps us build ethical ai
  this is a double edged sword statement
ethical ai has various aspects from data privacy to ai for all
tensor helps many users have the opportunity to try the latest ai advancement while they have no concern about their privacy
why
because the ai engine is running on the chip  and no data is sent to the cloud for further computation
on the other hand  the more tightly google binds ai software and hardware  the harder it will be for other companies to compete
i don t want to see days that other companies can not even compete on performing ai inference  i e   compete on using ai
we almost lost the game of model training to giant tech companies
it would be a nightmare if we lose the game on ai inference to them as well
that is why i believe  tensor helps us build ethical ai  is a double edged sword

In [30]:
for i in corpus:
    words = word_tokenize(i)
    for i in words:
        print(i)

tensor
and
tensorflow
a
powerful
combo
the
google
brain
team
developed
an
advanced
ai
framework
named
tensorflow
years
back
after
that
google
designed
its
own
processing
unit
named
tensor
processing
unit
or
tpu
to
perform
more
efficiently
with
the
tensorflow
the
invention
of
tpu
was
a
revolution
in
ai
that
has
significantly
expedited
the
training
of
huge
machine
learning
models
with
millions
or
billions
of
parameters
nevertheless
that
technology
could
not
be
used
in
low
power
devices
such
as
smartphones
in
edge
ai
the
entrance
of
google
into
the
ai
chip
manufacturing
club
for
low
power
devices
can
be
the
next
revolution
in
this
industry
many
companies
such
as
foghorn
and
blinkai
are
working
in
edge
ai
using
currently
existing
ai
chips
in
the
market
however
the
efficacy
that
google
can
create
by
the
combination
of
tensorflow
and
tensor
will
be
game
changing
welcome
to
the
club
google
tensor
is
an
ai
chip
designed
by
ai
isn
t
that
cool
the
story
is
started
from
an
article
published
in
nature
titles
a
graph
placement
methodology
for
fast
chip
design
to
design
a
processing
chip
there
is
a
crucial
step
referred
to
as
floor
planning
where
the
engineering
team
must
place
a
large
number
of
components
such
that
a
series
of
physical
requirements
including
power
consumption
and
performance
get
satisfied
i
don
t
go
further
into
its
details
as
i
am
also
not
an
expert
in
hardware
engineering
however
when
you
have
a
large
series
of
choices
to
make
with
a
series
of
constraints
ai
can
kick
in
you
may
remember
how
the
alphago
project
defeated
a
professional
human
go
player
this
is
exactly
the
same
tensor
is
the
real
outcome
of
this
project
that
is
a
new
milestone
in
the
ai
industry
kudos
google
tensor
helps
us
build
ethical
ai
this
is
a
double
edged
sword
statement
ethical
ai
has
various
aspects
from
data
privacy
to
ai
for
all
tensor
helps
many
users
have
the
opportunity
to
try
the
latest
ai
advancement
while
they
have
no
concern
about
their
privacy
why
because
the
ai
engine
is
running
on
the
chip
and
no
data
is
sent
to
the
cloud
for
further
computation
on
the
other
hand
the
more
tightly
google
binds
ai
software
and
hardware
the
harder
it
will
be
for
other
companies
to
compete
i
don
t
want
to
see
days
that
other
companies
can
not
even
compete
on
performing
ai
inference
i
e
compete
on
using
ai
we
almost
lost
the
game
of
model
training
to
giant
tech
companies
it
would
be
a
nightmare
if
we
lose
the
game
on
ai
inference
to
them
as
well
that
is
why
i
believe
tensor
helps
us
build
ethical
ai
is
a
double
edged
sword

In [31]:
x = 'Python'

'T' in x
'T' not in x

True

In [32]:
for i in corpus:
    words = word_tokenize(i)
    for i in words:
        if i not in stopwords.words('english'):
            print(stemmer.stem(i))

tensor
tensorflow
power
combo
googl
brain
team
develop
advanc
ai
framework
name
tensorflow
year
back
googl
design
process
unit
name
tensor
process
unit
tpu
perform
effici
tensorflow
invent
tpu
revolut
ai
significantli
expedit
train
huge
machin
learn
model
million
billion
paramet
nevertheless
technolog
could
use
low
power
devic
smartphon
edg
ai
entranc
googl
ai
chip
manufactur
club
low
power
devic
next
revolut
industri
mani
compani
foghorn
blinkai
work
edg
ai
use
current
exist
ai
chip
market
howev
efficaci
googl
creat
combin
tensorflow
tensor
game
chang
welcom
club
googl
tensor
ai
chip
design
ai
cool
stori
start
articl
publish
natur
titl
graph
placement
methodolog
fast
chip
design
design
process
chip
crucial
step
refer
floor
plan
engin
team
must
place
larg
number
compon
seri
physic
requir
includ
power
consumpt
perform
get
satisfi
go
detail
also
expert
hardwar
engin
howev
larg
seri
choic
make
seri
constraint
ai
kick
may
rememb
alphago
project
defeat
profession
human
go
player
exactli
tensor
real
outcom
project
new
mileston
ai
industri
kudo
googl
tensor
help
us
build
ethic
ai
doubl
edg
sword
statement
ethic
ai
variou
aspect
data
privaci
ai
tensor
help
mani
user
opportun
tri
latest
ai
advanc
concern
privaci
ai
engin
run
chip
data
sent
cloud
comput
hand
tightli
googl
bind
ai
softwar
hardwar
harder
compani
compet
want
see
day
compani
even
compet
perform
ai
infer
e
compet
use
ai
almost
lost
game
model
train
giant
tech
compani
would
nightmar
lose
game
ai
infer
well
believ
tensor
help
us
build
ethic
ai
doubl
edg
sword

# Lemmatization

In [34]:
lemma = WordNetLemmatizer()

In [35]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [36]:
for i in corpus:
    words = word_tokenize(i)
    for i in words:
        if i not in stopwords.words('english'):
            print(lemma.lemmatize(i))

tensor
tensorflow
powerful
combo
google
brain
team
developed
advanced
ai
framework
named
tensorflow
year
back
google
designed
processing
unit
named
tensor
processing
unit
tpu
perform
efficiently
tensorflow
invention
tpu
revolution
ai
significantly
expedited
training
huge
machine
learning
model
million
billion
parameter
nevertheless
technology
could
used
low
power
device
smartphones
edge
ai
entrance
google
ai
chip
manufacturing
club
low
power
device
next
revolution
industry
many
company
foghorn
blinkai
working
edge
ai
using
currently
existing
ai
chip
market
however
efficacy
google
create
combination
tensorflow
tensor
game
changing
welcome
club
google
tensor
ai
chip
designed
ai
cool
story
started
article
published
nature
title
graph
placement
methodology
fast
chip
design
design
processing
chip
crucial
step
referred
floor
planning
engineering
team
must
place
large
number
component
series
physical
requirement
including
power
consumption
performance
get
satisfied
go
detail
also
expert
hardware
engineering
however
large
series
choice
make
series
constraint
ai
kick
may
remember
alphago
project
defeated
professional
human
go
player
exactly
tensor
real
outcome
project
new
milestone
ai
industry
kudos
google
tensor
help
u
build
ethical
ai
double
edged
sword
statement
ethical
ai
various
aspect
data
privacy
ai
tensor
help
many
user
opportunity
try
latest
ai
advancement
concern
privacy
ai
engine
running
chip
data
sent
cloud
computation
hand
tightly
google
bind
ai
software
hardware
harder
company
compete
want
see
day
company
even
compete
performing
ai
inference
e
compete
using
ai
almost
lost
game
model
training
giant
tech
company
would
nightmare
lose
game
ai
inference
well
believe
tensor
help
u
build
ethical
ai
double
edged
sword

# Feature Extraction

In [38]:
corpus

['  tensor and tensorflow  a powerful combo   the google brain team developed an advanced ai framework named tensorflow years back ',
 'after that  google designed its own processing unit named tensor processing unit or tpu to perform more efficiently with the tensorflow ',
 'the invention of tpu was a revolution in ai that has significantly expedited the training of huge machine learning models with millions  or  billions  of parameters ',
 'nevertheless  that technology could not be used in low power devices such as smartphones in edge ai ',
 'the entrance of google into the ai chip manufacturing club for low power devices can be the next revolution in this industry ',
 'many companies such as foghorn and blinkai are working in edge ai using currently existing ai chips in the market ',
 'however  the efficacy that google can create by the combination of tensorflow and tensor will be game changing ',
 'welcome to the club  google ',
 '  tensor is an ai chip designed by ai ',
 '  isn t that cool ',
 'the story is started from an article published in nature titles  a graph placement methodology for fast chip design  ',
 'to design a processing chip  there is a crucial step referred to as  floor planning  where the engineering team must place a large number of components such that a series of physical requirements including power consumption and performance get satisfied ',
 'i don t go further into its details as i am also not an expert in hardware engineering ',
 'however  when you have a large series of choices to make with a series of constraints ai can kick in ',
 'you may remember how the alphago project defeated a professional human go player ',
 'this is exactly the same ',
 'tensor is the real outcome of this project that is a new milestone in the ai industry ',
 'kudos  google ',
 '  tensor helps us build ethical ai ',
 '  this is a double edged sword statement ',
 'ethical ai has various aspects from data privacy to ai for all ',
 'tensor helps many users have the opportunity to try the latest ai advancement while they have no concern about their privacy ',
 'why ',
 'because the ai engine is running on the chip  and no data is sent to the cloud for further computation ',
 'on the other hand  the more tightly google binds ai software and hardware  the harder it will be for other companies to compete ',
 'i don t want to see days that other companies can not even compete on performing ai inference  i e   compete on using ai ',
 'we almost lost the game of model training to giant tech companies ',
 'it would be a nightmare if we lose the game on ai inference to them as well ',
 'that is why i believe  tensor helps us build ethical ai  is a double edged sword ']

In [39]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# BOW

In [41]:
cv = CountVectorizer()

x = cv.fit_transform(corpus)
x

<29x216 sparse matrix of type '<class 'numpy.int64'>'
	with 398 stored elements in Compressed Sparse Row format>

In [42]:
# To convert into array data structure
x.toarray()

array([[0, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [43]:
pd.DataFrame(x.toarray())

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
0,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,1
14,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,2,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,1,0,1,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
23,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
25,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
28,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [44]:
# in order to see the unique words present for the columns
cv.vocabulary_

{'tensor': 180,
 'and': 11,
 'tensorflow': 181,
 'powerful': 151,
 'combo': 34,
 'the': 183,
 'google': 81,
 'brain': 23,
 'team': 177,
 'developed': 53,
 'an': 10,
 'advanced': 1,
 'ai': 4,
 'framework': 74,
 'named': 125,
 'years': 214,
 'back': 16,
 'after': 3,
 'that': 182,
 'designed': 51,
 'its': 103,
 'own': 140,
 'processing': 153,
 'unit': 195,
 'or': 137,
 'tpu': 192,
 'to': 191,
 'perform': 142,
 'more': 123,
 'efficiently': 60,
 'with': 211,
 'invention': 99,
 'of': 134,
 'was': 202,
 'revolution': 161,
 'in': 94,
 'has': 86,
 'significantly': 168,
 'expedited': 68,
 'training': 193,
 'huge': 91,
 'machine': 112,
 'learning': 108,
 'models': 122,
 'millions': 120,
 'billions': 20,
 'parameters': 141,
 'nevertheless': 127,
 'technology': 179,
 'could': 43,
 'not': 132,
 'be': 17,
 'used': 197,
 'low': 111,
 'power': 150,
 'devices': 54,
 'such': 175,
 'as': 14,
 'smartphones': 169,
 'edge': 57,
 'entrance': 63,
 'into': 98,
 'chip': 28,
 'manufacturing': 114,
 'club': 32,
 'for': 73,
 'can': 26,
 'next': 129,
 'this': 188,
 'industry': 96,
 'many': 115,
 'companies': 35,
 'foghorn': 72,
 'blinkai': 22,
 'are': 12,
 'working': 212,
 'using': 199,
 'currently': 46,
 'existing': 67,
 'chips': 29,
 'market': 116,
 'however': 90,
 'efficacy': 59,
 'create': 44,
 'by': 25,
 'combination': 33,
 'will': 210,
 'game': 77,
 'changing': 27,
 'welcome': 204,
 'is': 100,
 'isn': 101,
 'cool': 42,
 'story': 174,
 'started': 171,
 'from': 75,
 'article': 13,
 'published': 156,
 'nature': 126,
 'titles': 190,
 'graph': 82,
 'placement': 147,
 'methodology': 118,
 'fast': 70,
 'design': 50,
 'there': 186,
 'crucial': 45,
 'step': 173,
 'referred': 158,
 'floor': 71,
 'planning': 148,
 'where': 207,
 'engineering': 62,
 'must': 124,
 'place': 146,
 'large': 106,
 'number': 133,
 'components': 37,
 'series': 167,
 'physical': 145,
 'requirements': 160,
 'including': 95,
 'consumption': 41,
 'performance': 143,
 'get': 78,
 'satisfied': 164,
 'don': 55,
 'go': 80,
 'further': 76,
 'details': 52,
 'am': 9,
 'also': 8,
 'expert': 69,
 'hardware': 85,
 'when': 206,
 'you': 215,
 'have': 87,
 'choices': 30,
 'make': 113,
 'constraints': 40,
 'kick': 104,
 'may': 117,
 'remember': 159,
 'how': 89,
 'alphago': 7,
 'project': 155,
 'defeated': 49,
 'professional': 154,
 'human': 92,
 'player': 149,
 'exactly': 66,
 'same': 163,
 'real': 157,
 'outcome': 139,
 'new': 128,
 'milestone': 119,
 'kudos': 105,
 'helps': 88,
 'us': 196,
 'build': 24,
 'ethical': 64,
 'double': 56,
 'edged': 58,
 'sword': 176,
 'statement': 172,
 'various': 200,
 'aspects': 15,
 'data': 47,
 'privacy': 152,
 'all': 5,
 'users': 198,
 'opportunity': 136,
 'try': 194,
 'latest': 107,
 'advancement': 2,
 'while': 208,
 'they': 187,
 'no': 131,
 'concern': 39,
 'about': 0,
 'their': 184,
 'why': 209,
 'because': 18,
 'engine': 61,
 'running': 162,
 'on': 135,
 'sent': 166,
 'cloud': 31,
 'computation': 38,
 'other': 138,
 'hand': 83,
 'tightly': 189,
 'binds': 21,
 'software': 170,
 'harder': 84,
 'it': 102,
 'compete': 36,
 'want': 201,
 'see': 165,
 'days': 48,
 'even': 65,
 'performing': 144,
 'inference': 97,
 'we': 203,
 'almost': 6,
 'lost': 110,
 'model': 121,
 'giant': 79,
 'tech': 178,
 'would': 213,
 'nightmare': 130,
 'if': 93,
 'lose': 109,
 'them': 185,
 'well': 205,
 'believe': 19}

In [45]:
cv.get_feature_names_out()

array(['about', 'advanced', 'advancement', 'after', 'ai', 'all', 'almost',
       'alphago', 'also', 'am', 'an', 'and', 'are', 'article', 'as',
       'aspects', 'back', 'be', 'because', 'believe', 'billions', 'binds',
       'blinkai', 'brain', 'build', 'by', 'can', 'changing', 'chip',
       'chips', 'choices', 'cloud', 'club', 'combination', 'combo',
       'companies', 'compete', 'components', 'computation', 'concern',
       'constraints', 'consumption', 'cool', 'could', 'create', 'crucial',
       'currently', 'data', 'days', 'defeated', 'design', 'designed',
       'details', 'developed', 'devices', 'don', 'double', 'edge',
       'edged', 'efficacy', 'efficiently', 'engine', 'engineering',
       'entrance', 'ethical', 'even', 'exactly', 'existing', 'expedited',
       'expert', 'fast', 'floor', 'foghorn', 'for', 'framework', 'from',
       'further', 'game', 'get', 'giant', 'go', 'google', 'graph', 'hand',
       'harder', 'hardware', 'has', 'have', 'helps', 'how', 'however',
       'huge', 'human', 'if', 'in', 'including', 'industry', 'inference',
       'into', 'invention', 'is', 'isn', 'it', 'its', 'kick', 'kudos',
       'large', 'latest', 'learning', 'lose', 'lost', 'low', 'machine',
       'make', 'manufacturing', 'many', 'market', 'may', 'methodology',
       'milestone', 'millions', 'model', 'models', 'more', 'must',
       'named', 'nature', 'nevertheless', 'new', 'next', 'nightmare',
       'no', 'not', 'number', 'of', 'on', 'opportunity', 'or', 'other',
       'outcome', 'own', 'parameters', 'perform', 'performance',
       'performing', 'physical', 'place', 'placement', 'planning',
       'player', 'power', 'powerful', 'privacy', 'processing',
       'professional', 'project', 'published', 'real', 'referred',
       'remember', 'requirements', 'revolution', 'running', 'same',
       'satisfied', 'see', 'sent', 'series', 'significantly',
       'smartphones', 'software', 'started', 'statement', 'step', 'story',
       'such', 'sword', 'team', 'tech', 'technology', 'tensor',
       'tensorflow', 'that', 'the', 'their', 'them', 'there', 'they',
       'this', 'tightly', 'titles', 'to', 'tpu', 'training', 'try',
       'unit', 'us', 'used', 'users', 'using', 'various', 'want', 'was',
       'we', 'welcome', 'well', 'when', 'where', 'while', 'why', 'will',
       'with', 'working', 'would', 'years', 'you'], dtype=object)

In [46]:
corpus[0]

corpus[5]

'many companies such as foghorn and blinkai are working in edge ai using currently existing ai chips in the market '

In [47]:
pd.DataFrame(x.toarray(), columns= cv.get_feature_names_out())

,about,advanced,advancement,after,ai,all,almost,alphago,also,am,...,when,where,while,why,will,with,working,would,years,you
0,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,1
14,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,2,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,1,0,1,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
23,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
25,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
28,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

# Binary Weights

In [49]:
cv = CountVectorizer(binary=True)

x = cv.fit_transform(corpus)
pd.DataFrame(x.toarray(), columns= cv.get_feature_names_out())

,about,advanced,advancement,after,ai,all,almost,alphago,also,am,...,when,where,while,why,will,with,working,would,years,you
0,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,1
14,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,1,0,1,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
23,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
25,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
28,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

# Tf-IDF

In [51]:
tf = TfidfVectorizer()

data = tf.fit_transform(corpus)
data.toarray()

array([[0.        , 0.26420014, 0.        , ..., 0.        , 0.26420014,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.29867304, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [52]:
tf.vocabulary_

{'tensor': 180,
 'and': 11,
 'tensorflow': 181,
 'powerful': 151,
 'combo': 34,
 'the': 183,
 'google': 81,
 'brain': 23,
 'team': 177,
 'developed': 53,
 'an': 10,
 'advanced': 1,
 'ai': 4,
 'framework': 74,
 'named': 125,
 'years': 214,
 'back': 16,
 'after': 3,
 'that': 182,
 'designed': 51,
 'its': 103,
 'own': 140,
 'processing': 153,
 'unit': 195,
 'or': 137,
 'tpu': 192,
 'to': 191,
 'perform': 142,
 'more': 123,
 'efficiently': 60,
 'with': 211,
 'invention': 99,
 'of': 134,
 'was': 202,
 'revolution': 161,
 'in': 94,
 'has': 86,
 'significantly': 168,
 'expedited': 68,
 'training': 193,
 'huge': 91,
 'machine': 112,
 'learning': 108,
 'models': 122,
 'millions': 120,
 'billions': 20,
 'parameters': 141,
 'nevertheless': 127,
 'technology': 179,
 'could': 43,
 'not': 132,
 'be': 17,
 'used': 197,
 'low': 111,
 'power': 150,
 'devices': 54,
 'such': 175,
 'as': 14,
 'smartphones': 169,
 'edge': 57,
 'entrance': 63,
 'into': 98,
 'chip': 28,
 'manufacturing': 114,
 'club': 32,
 'for': 73,
 'can': 26,
 'next': 129,
 'this': 188,
 'industry': 96,
 'many': 115,
 'companies': 35,
 'foghorn': 72,
 'blinkai': 22,
 'are': 12,
 'working': 212,
 'using': 199,
 'currently': 46,
 'existing': 67,
 'chips': 29,
 'market': 116,
 'however': 90,
 'efficacy': 59,
 'create': 44,
 'by': 25,
 'combination': 33,
 'will': 210,
 'game': 77,
 'changing': 27,
 'welcome': 204,
 'is': 100,
 'isn': 101,
 'cool': 42,
 'story': 174,
 'started': 171,
 'from': 75,
 'article': 13,
 'published': 156,
 'nature': 126,
 'titles': 190,
 'graph': 82,
 'placement': 147,
 'methodology': 118,
 'fast': 70,
 'design': 50,
 'there': 186,
 'crucial': 45,
 'step': 173,
 'referred': 158,
 'floor': 71,
 'planning': 148,
 'where': 207,
 'engineering': 62,
 'must': 124,
 'place': 146,
 'large': 106,
 'number': 133,
 'components': 37,
 'series': 167,
 'physical': 145,
 'requirements': 160,
 'including': 95,
 'consumption': 41,
 'performance': 143,
 'get': 78,
 'satisfied': 164,
 'don': 55,
 'go': 80,
 'further': 76,
 'details': 52,
 'am': 9,
 'also': 8,
 'expert': 69,
 'hardware': 85,
 'when': 206,
 'you': 215,
 'have': 87,
 'choices': 30,
 'make': 113,
 'constraints': 40,
 'kick': 104,
 'may': 117,
 'remember': 159,
 'how': 89,
 'alphago': 7,
 'project': 155,
 'defeated': 49,
 'professional': 154,
 'human': 92,
 'player': 149,
 'exactly': 66,
 'same': 163,
 'real': 157,
 'outcome': 139,
 'new': 128,
 'milestone': 119,
 'kudos': 105,
 'helps': 88,
 'us': 196,
 'build': 24,
 'ethical': 64,
 'double': 56,
 'edged': 58,
 'sword': 176,
 'statement': 172,
 'various': 200,
 'aspects': 15,
 'data': 47,
 'privacy': 152,
 'all': 5,
 'users': 198,
 'opportunity': 136,
 'try': 194,
 'latest': 107,
 'advancement': 2,
 'while': 208,
 'they': 187,
 'no': 131,
 'concern': 39,
 'about': 0,
 'their': 184,
 'why': 209,
 'because': 18,
 'engine': 61,
 'running': 162,
 'on': 135,
 'sent': 166,
 'cloud': 31,
 'computation': 38,
 'other': 138,
 'hand': 83,
 'tightly': 189,
 'binds': 21,
 'software': 170,
 'harder': 84,
 'it': 102,
 'compete': 36,
 'want': 201,
 'see': 165,
 'days': 48,
 'even': 65,
 'performing': 144,
 'inference': 97,
 'we': 203,
 'almost': 6,
 'lost': 110,
 'model': 121,
 'giant': 79,
 'tech': 178,
 'would': 213,
 'nightmare': 130,
 'if': 93,
 'lose': 109,
 'them': 185,
 'well': 205,
 'believe': 19}

In [53]:
x = pd.DataFrame(data.toarray(), columns=tf.get_feature_names_out())
x

,about,advanced,advancement,after,ai,all,almost,alphago,also,am,...,when,where,while,why,will,with,working,would,years,you
0,0.000000,0.2642,0.000000,0.000000,0.111720,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.2642,0.000000
1,0.000000,0.0000,0.000000,0.230918,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.187753,0.000000,0.000000,0.0000,0.000000
2,0.000000,0.0000,0.000000,0.000000,0.093004,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.178827,0.000000,0.000000,0.0000,0.000000
3,0.000000,0.0000,0.000000,0.000000,0.120739,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
4,0.000000,0.0000,0.000000,0.000000,0.113623,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
5,0.000000,0.0000,0.000000,0.000000,0.219569,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.259624,0.000000,0.0000,0.000000
6,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.264670,0.000000,0.000000,0.000000,0.0000,0.000000
7,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
8,0.000000,0.0000,0.000000,0.000000,0.419187,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
9,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
10,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
11,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.185738,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
12,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.29324,0.29324,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
13,0.000000,0.0000,0.000000,0.000000,0.109396,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.258705,0.000000,0.000000,0.000000,0.000000,0.210345,0.000000,0.000000,0.0000,0.230416
14,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.307936,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.274264
15,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
16,0.000000,0.0000,0.000000,0.000000,0.134883,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
17,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
18,0.000000,0.0000,0.000000,0.000000,0.227965,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
19,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
20,0.000000,0.0000,0.000000,0.000000,0.293347,0.346861,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
21,0.237845,0.0000,0.237845,0.000000,0.100575,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.237845,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
22,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
23,0.000000,0.0000,0.000000,0.000000,0.114125,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
24,0.000000,0.0000,0.000000,0.000000,0.102456,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.215799,0.000000,0.000000,0.000000,0.0000,0.000000
25,0.000000,0.0000,0.000000,0.000000,0.206884,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
26,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.340215,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
27,0.000000,0.0000,0.000000,0.000000,0.126297,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.298673,0.0000,0.000000
28,0.000000,0.0000,0.000000,0.000000,0.138310,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.291317,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000