In [ ]:
# importing libraries
# !pip install tensorflow

In [ ]:
from typing_extensions import TypeForm
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings("ignore")

#  Loading the data

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/bhabani0807/Data-sets/refs/heads/main/Churn_Modelling.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

load the data

In [ ]:
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

# **Data transformation**

In [ ]:
df = pd.get_dummies(data=df, columns=['Geography','Gender'])
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,True,False,False,True,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,False,True,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,True,False,False,True,False
3,699,39,1,0.00,2,0,0,93826.63,0,True,False,False,True,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,True,False,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,0,True,False,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,1,True,False,False,True,False
9998,772,42,3,75075.31,2,1,0,92888.52,1,False,True,False,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,0,True,False,False,True,False

# **Model Building**

In [ ]:
sc = StandardScaler()
x = df.drop(columns=['Exited'])
y = df['Exited']

In [ ]:
x = sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20, random_state=1)

In [ ]:
#Initialize model
ann = Sequential()

#Add hidden layer
ann.add(Dense(units=10,activation='relu'))

#Add output layer
ann.add(Dense(units=1, activation='sigmoid'))

#Establish the connection between the layers
ann.compile(optimizer = 'adadelta',loss='binary_crossentropy',metrics=['accuracy'])

#Fit the data
ann.fit(xtrain,ytrain, epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6245 - loss: 0.6772
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6323 - loss: 0.6703
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6349 - loss: 0.6715
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6335 - loss: 0.6693
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6350 - loss: 0.6683
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6434 - loss: 0.6588
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6362 - loss: 0.6685
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6344 - loss: 0.6723
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6461 - loss: 0.6657
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6399 - loss: 0.6614
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6462 - loss: 0.6600
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6385 - loss: 0.6664
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6356 - loss: 0.6660
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6447 - loss: 0.6573
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6354 - loss: 0.6674
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6466 - loss: 0.6667
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6453 - loss: 0.6583
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6542 - loss: 0.6587
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6620 - loss: 0.6530
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6389 - loss: 0.6648
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6527 - loss: 0.6643
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6416 - loss: 0.6592
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6502 - loss: 0.6535
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6487 - loss: 0.6535
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6582 - loss: 0.6515
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6546 - loss: 0.6555
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6472 - loss: 0.6634
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6603 - loss: 0.6531
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6460 - loss: 0.6585
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6522 - loss: 0.6543
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6599 - loss: 0.6514
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6618 - loss: 0.6527
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6504 - loss: 0.6609
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6447 - loss: 0.6585
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6644 - loss: 0.6489
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6648 - loss: 0.6534
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6632 - loss: 0.6550
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.6485
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6650 - loss: 0.6496
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6612 - loss: 0.6484
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6602 - loss: 0.6480
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6540 - loss: 0.6546
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6743 - loss: 0.6392
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6712 - loss: 0.6415
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6620 - loss: 0.6425
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6712 - loss: 0.6423
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6625 - loss: 0.6474
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6729 - loss: 0.6407
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6692 - loss: 0.6428
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6740 - loss: 0.6394
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6702 - loss: 0.6424
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6682 - loss: 0.6440
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6786 - loss: 0.6363
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6810 - loss: 0.6372
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6791 - loss: 0.6373
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.6321
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6843 - loss: 0.6348
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6892 - loss: 0.6302
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6759 - loss: 0.6355
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6741 - loss: 0.6404
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6834 - loss: 0.6289
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6765 - loss: 0.6354
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6780 - loss: 0.6341
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6778 - loss: 0.6368
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6760 - loss: 0.6377
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6839 - loss: 0.6303
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6837 - loss: 0.6307
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6810 - loss: 0.6327
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6784 - loss: 0.6339
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6759 - loss: 0.6376
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6851 - loss: 0.6310
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6837 - loss: 0.6339
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.6349
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6953 - loss: 0.6222
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6990 - loss: 0.6200
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6850 - loss: 0.6317
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6828 - loss: 0.6278
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6930 - loss: 0.6262
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6876 - loss: 0.6237
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6957 - loss: 0.6183
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6935 - loss: 0.6226
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6882 - loss: 0.6330
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6980 - loss: 0.6174
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6931 - loss: 0.6268
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6972 - loss: 0.6211
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6935 - loss: 0.6255
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6827 - loss: 0.6337
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6811 - loss: 0.6358
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6924 - loss: 0.6280
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6933 - loss: 0.6219
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6961 - loss: 0.6226
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6977 - loss: 0.6227
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6974 - loss: 0.6219
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6981 - loss: 0.6155
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7146 - loss: 0.6088
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6975 - loss: 0.6172
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6976 - loss: 0.6148
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6986 - loss: 0.6187
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6965 - loss: 0.6223
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6995 - loss: 0.6176

In [ ]:
xtest

array([[-1.04014895,  0.77028538, -1.04175968, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 0.3049319 , -0.4693113 , -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-1.23673768,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [-0.86425376, -0.4693113 ,  1.72446358, ...,  1.74273971,
        -0.91241915,  0.91241915],
       [-0.30552787, -0.85072567, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.0462625 ,  1.24705333,  1.37868567, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [ ]:
ypred = ann.predict(xtest)
ypred

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([[0.15017541],
       [0.35889232],
       [0.06145074],
       ...,
       [0.4233703 ],
       [0.40390152],
       [0.47451472]], dtype=float32)

In [ ]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [ ]:
ypred > 0.05

array([[ True],
       [ True],
       [ True],
       ...,
       [ True],
       [ True],
       [ True]])

In [ ]:
ypred = ypred > 0.05
ypred

array([[ True],
       [ True],
       [ True],
       ...,
       [ True],
       [ True],
       [ True]])

In [ ]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [ ]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.50      0.00      0.00      1585
           1       0.21      0.99      0.34       415

    accuracy                           0.21      2000
   macro avg       0.35      0.50      0.17      2000
weighted avg       0.44      0.21      0.07      2000

# **Hyper parameter tuning**

In [ ]:
#! pip install keras-tuner

In [ ]:
import keras_tuner as kt

In [ ]:
def optimizer_selection(hp):
    #initialize the model
    model = Sequential()
    #Add hidden layer
    model.add(Dense(units=10, activation='relu'))
    #Add output layer
    model.add(Dense(units=1, activation='sigmoid'))
    #Optimizer selection
    optim = hp.Choice('optimizer', values = ['sgd','adam','rmsprop'])
    model.compile(optimizer=optim, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return model

In [ ]:
tuner = kt.RandomSearch(
    optimizer_selection,
    objective='val_accuracy',
    max_trials=3
)

In [ ]:
tuner.search(xtrain,ytrain, epochs = 3, validation_data = (xtest,ytest))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.8180000185966492

Best val_accuracy So Far: 0.8180000185966492
Total elapsed time: 00h 00m 09s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]
model.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8128 - loss: 0.4182 - val_accuracy: 0.8250 - val_loss: 0.4026
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8187 - loss: 0.4093 - val_accuracy: 0.8335 - val_loss: 0.3931
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8329 - loss: 0.3976 - val_accuracy: 0.8370 - val_loss: 0.3831
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8301 - loss: 0.3975 - val_accuracy: 0.8435 - val_loss: 0.3756
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8449 - loss: 0.3693 - val_accuracy: 0.8470 - val_loss: 0.3688
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8441 - loss: 0.3721 - val_accuracy: 0.8460 - val_loss: 0.3640
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8468 - loss: 0.3751 - val_accuracy: 0.8485 - val_loss: 0.3607
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8506 - loss: 0.3657 - val_accuracy: 0.8495 - val_loss: 0.3568
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8580 - loss: 0.3493 - val_accuracy: 0.8505 - val_loss: 0.3540
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8574 - loss: 0.3571 - val_accuracy: 0.8510 - val_loss: 0.3527
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8580 - loss: 0.3568 - val_accuracy: 0.8515 - val_loss: 0.3502
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8518 - loss: 0.3550 - val_accuracy: 0.8520 - val_loss: 0.3482
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8558 - loss: 0.3640 - val_accuracy: 0.8550 - val_loss: 0.3464
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8627 - loss: 0.3399 - val_accuracy: 0.8545 - val_loss: 0.3456
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8563 - loss: 0.3491 - val_accuracy: 0.8555 - val_loss: 0.3450
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8589 - loss: 0.3465 - val_accuracy: 0.8555 - val_loss: 0.3442
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8519 - loss: 0.3553 - val_accuracy: 0.8565 - val_loss: 0.3442
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8659 - loss: 0.3377 - val_accuracy: 0.8575 - val_loss: 0.3425
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8637 - loss: 0.3444 - val_accuracy: 0.8565 - val_loss: 0.3421
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8574 - loss: 0.3450 - val_accuracy: 0.8570 - val_loss: 0.3411
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8620 - loss: 0.3405 - val_accuracy: 0.8560 - val_loss: 0.3406
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8597 - loss: 0.3428 - val_accuracy: 0.8575 - val_loss: 0.3406
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8557 - loss: 0.3506 - val_accuracy: 0.8575 - val_loss: 0.3408
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8624 - loss: 0.3438 - val_accuracy: 0.8580 - val_loss: 0.3405
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8623 - loss: 0.3398 - val_accuracy: 0.8585 - val_loss: 0.3397
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8615 - loss: 0.3369 - val_accuracy: 0.8570 - val_loss: 0.3404
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8616 - loss: 0.3408 - val_accuracy: 0.8570 - val_loss: 0.3400
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8685 - loss: 0.3390 - val_accuracy: 0.8575 - val_loss: 0.3397
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8659 - loss: 0.3379 - val_accuracy: 0.8560 - val_loss: 0.3397
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8609 - loss: 0.3372 - val_accuracy: 0.8580 - val_loss: 0.3405
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8609 - loss: 0.3445 - val_accuracy: 0.8560 - val_loss: 0.3388
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8694 - loss: 0.3272 - val_accuracy: 0.8565 - val_loss: 0.3389
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8649 - loss: 0.3344 - val_accuracy: 0.8570 - val_loss: 0.3396
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8574 - loss: 0.3473 - val_accuracy: 0.8595 - val_loss: 0.3382
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8626 - loss: 0.3325 - val_accuracy: 0.8565 - val_loss: 0.3382
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8658 - loss: 0.3349 - val_accuracy: 0.8565 - val_loss: 0.3389
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8615 - loss: 0.3401 - val_accuracy: 0.8595 - val_loss: 0.3378
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8607 - loss: 0.3476 - val_accuracy: 0.8570 - val_loss: 0.3391
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8578 - loss: 0.3472 - val_accuracy: 0.8575 - val_loss: 0.3378
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8612 - loss: 0.3418 - val_accuracy: 0.8570 - val_loss: 0.3384
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8637 - loss: 0.3245 - val_accuracy: 0.8590 - val_loss: 0.3388
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8606 - loss: 0.3400 - val_accuracy: 0.8570 - val_loss: 0.3385
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8619 - loss: 0.3404 - val_accuracy: 0.8575 - val_loss: 0.3389
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8641 - loss: 0.3404 - val_accuracy: 0.8580 - val_loss: 0.3375
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8665 - loss: 0.3304 - val_accuracy: 0.8590 - val_loss: 0.3377
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8595 - loss: 0.3380 - val_accuracy: 0.8585 - val_loss: 0.3368
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8548 - loss: 0.3557 - val_accuracy: 0.8585 - val_loss: 0.3384
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8627 - loss: 0.3315 - val_accuracy: 0.8570 - val_loss: 0.3388
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8606 - loss: 0.3392 - val_accuracy: 0.8595 - val_loss: 0.3378
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8631 - loss: 0.3336 - val_accuracy: 0.8585 - val_loss: 0.3375
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8564 - loss: 0.3456 - val_accuracy: 0.8575 - val_loss: 0.3382
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8617 - loss: 0.3356 - val_accuracy: 0.8570 - val_loss: 0.3368
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8589 - loss: 0.3427 - val_accuracy: 0.8595 - val_loss: 0.3362
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8630 - loss: 0.3414 - val_accuracy: 0.8585 - val_loss: 0.3370
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8611 - loss: 0.3326 - val_accuracy: 0.8580 - val_loss: 0.3379
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8536 - loss: 0.3408 - val_accuracy: 0.8590 - val_loss: 0.3385
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8606 - loss: 0.3362 - val_accuracy: 0.8560 - val_loss: 0.3377
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8663 - loss: 0.3331 - val_accuracy: 0.8565 - val_loss: 0.3372
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8613 - loss: 0.3425 - val_accuracy: 0.8585 - val_loss: 0.3376
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8641 - loss: 0.3295 - val_accuracy: 0.8570 - val_loss: 0.3371
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8581 - loss: 0.3438 - val_accuracy: 0.8545 - val_loss: 0.3373
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8645 - loss: 0.3327 - val_accuracy: 0.8570 - val_loss: 0.3370
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8546 - loss: 0.3459 - val_accuracy: 0.8580 - val_loss: 0.3367
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8695 - loss: 0.3282 - val_accuracy: 0.8575 - val_loss: 0.3363
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8686 - loss: 0.3282 - val_accuracy: 0.8580 - val_loss: 0.3363
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8605 - loss: 0.3451 - val_accuracy: 0.8565 - val_loss: 0.3371
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8690 - loss: 0.3272 - val_accuracy: 0.8580 - val_loss: 0.3363
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8571 - loss: 0.3467 - val_accuracy: 0.8595 - val_loss: 0.3361
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8627 - loss: 0.3371 - val_accuracy: 0.8560 - val_loss: 0.3375
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8572 - loss: 0.3528 - val_accuracy: 0.8595 - val_loss: 0.3379
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8628 - loss: 0.3315 - val_accuracy: 0.8580 - val_loss: 0.3371
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8633 - loss: 0.3381 - val_accuracy: 0.8590 - val_loss: 0.3373
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8622 - loss: 0.3370 - val_accuracy: 0.8585 - val_loss: 0.3366
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8592 - loss: 0.3420 - val_accuracy: 0.8590 - val_loss: 0.3378
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8621 - loss: 0.3477 - val_accuracy: 0.8560 - val_loss: 0.3367
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8564 - loss: 0.3448 - val_accuracy: 0.8585 - val_loss: 0.3365
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8661 - loss: 0.3271 - val_accuracy: 0.8600 - val_loss: 0.3367
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8647 - loss: 0.3292 - val_accuracy: 0.8615 - val_loss: 0.3368
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8669 - loss: 0.3325 - val_accuracy: 0.8590 - val_loss: 0.3364
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8613 - loss: 0.3392 - val_accuracy: 0.8580 - val_loss: 0.3376
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8562 - loss: 0.3448 - val_accuracy: 0.8570 - val_loss: 0.3366
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8613 - loss: 0.3428 - val_accuracy: 0.8575 - val_loss: 0.3367
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8583 - loss: 0.3475 - val_accuracy: 0.8590 - val_loss: 0.3377
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8633 - loss: 0.3311 - val_accuracy: 0.8600 - val_loss: 0.3356
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8640 - loss: 0.3347 - val_accuracy: 0.8580 - val_loss: 0.3368
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8590 - loss: 0.3354 - val_accuracy: 0.8565 - val_loss: 0.3374
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8596 - loss: 0.3390 - val_accuracy: 0.8605 - val_loss: 0.3361
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8543 - loss: 0.3458 - val_accuracy: 0.8590 - val_loss: 0.3357
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8631 - loss: 0.3376 - val_accuracy: 0.8590 - val_loss: 0.3377
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8601 - loss: 0.3410 - val_accuracy: 0.8610 - val_loss: 0.3351
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8590 - loss: 0.3379 - val_accuracy: 0.8575 - val_loss: 0.3360
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8626 - loss: 0.3367 - val_accuracy: 0.8580 - val_loss: 0.3357
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8652 - loss: 0.3287 - val_accuracy: 0.8580 - val_loss: 0.3356
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8538 - loss: 0.3444 - val_accuracy: 0.8590 - val_loss: 0.3369
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8669 - loss: 0.3290 - val_accuracy: 0.8585 - val_loss: 0.3362
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8591 - loss: 0.3379 - val_accuracy: 0.8585 - val_loss: 0.3357
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8612 - loss: 0.3356 - val_accuracy: 0.8570 - val_loss: 0.3368
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8592 - loss: 0.3394 - val_accuracy: 0.8575 - val_loss: 0.3375
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8671 - loss: 0.3323 - val_accuracy: 0.8575 - val_loss: 0.3375
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8520 - loss: 0.3519 - val_accuracy: 0.8565 - val_loss: 0.3371

In [ ]:
model.evaluate(xtrain,ytrain)

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8656 - loss: 0.3381

[0.3361148238182068, 0.8622499704360962]

# **Regression**

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/aishwaryamate/Datasets/main/Regression.csv")
df

          price     feature1     feature2
0    461.527929   999.787558   999.766096
1    548.130012   998.861615  1001.042403
2    410.297162  1000.070267   998.844015
3    540.382220   999.952251  1000.440940
4    546.024553  1000.446011  1000.338531
..          ...          ...          ...
995  476.526078  1000.018988   999.672732
996  457.313186   998.855379  1000.020026
997  456.720993  1001.451646   998.847605
998  403.315576  1000.771023   998.562851
999  599.367094   999.232244  1001.451407

[1000 rows x 3 columns]

In [ ]:
x = df.iloc[:,1:]
y = df["price"]

In [ ]:
x= sc.fit_transform(x)
x

array([[-0.23277509, -0.22551031],
       [-1.18389307,  1.12100979],
       [ 0.05762098, -1.19831827],
       ...,
       [ 1.47655818, -1.19452982],
       [ 0.77742978, -1.49494959],
       [-0.80318737,  1.55251428]])

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2, random_state =1)

In [ ]:
ann = Sequential()

ann.add(Dense(units = 30, activation="relu"))
ann.add(Dense(units = 20, activation="relu"))

ann.add(Dense(units = 1))

ann.compile(optimizer = 'adam', loss = 'mse')

ann.fit(xtrain,ytrain, epochs= 100 , validation_data= (xtest,ytest))

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 251061.5000 - val_loss: 262321.5312
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 254746.5469 - val_loss: 261536.5625
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 254483.4844 - val_loss: 260266.8438
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 252426.7969 - val_loss: 258239.6875
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 256230.6719 - val_loss: 255140.9375
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 251342.3750 - val_loss: 250777.0469
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 247121.0156 - val_loss: 244774.8594
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 235057.7344 - val_loss: 236990.0000
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 230078.8125 - val_loss: 227171.0781
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 214372.4219 - val_loss: 215292.1250
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 200511.5938 - val_loss: 201435.4375
Epoch 12/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 186831.2188 - val_loss: 185736.2969
Epoch 13/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 171921.1719 - val_loss: 168361.5781
Epoch 14/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 158249.8281 - val_loss: 149950.7344
Epoch 15/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 136324.1094 - val_loss: 131011.9531
Epoch 16/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 118960.7578 - val_loss: 111874.7891
Epoch 17/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 101444.1094 - val_loss: 93202.6719
Epoch 18/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 84303.0547 - val_loss: 75866.0078
Epoch 19/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 66361.1641 - val_loss: 60247.9844
Epoch 20/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 50751.6172 - val_loss: 46787.0742
Epoch 21/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 41563.7617 - val_loss: 35372.3984
Epoch 22/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 30054.7305 - val_loss: 26468.8457
Epoch 23/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21789.6172 - val_loss: 19750.2715
Epoch 24/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16965.8047 - val_loss: 14876.1064
Epoch 25/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12237.8682 - val_loss: 11588.7363
Epoch 26/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10516.5723 - val_loss: 9357.7783
Epoch 27/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7815.7075 - val_loss: 7866.4683
Epoch 28/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7590.0132 - val_loss: 6939.2324
Epoch 29/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6761.3384 - val_loss: 6288.8149
Epoch 30/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5952.2329 - val_loss: 5826.6895
Epoch 31/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6059.4775 - val_loss: 5496.2017
Epoch 32/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5093.8311 - val_loss: 5184.2539
Epoch 33/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5088.0381 - val_loss: 4935.6279
Epoch 34/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5073.3706 - val_loss: 4701.6011
Epoch 35/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4715.8452 - val_loss: 4484.8306
Epoch 36/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4214.2095 - val_loss: 4290.0640
Epoch 37/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4727.3252 - val_loss: 4075.7588
Epoch 38/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4050.0291 - val_loss: 3884.0100
Epoch 39/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3564.1914 - val_loss: 3701.7109
Epoch 40/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3490.0676 - val_loss: 3530.6313
Epoch 41/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3561.9792 - val_loss: 3358.1001
Epoch 42/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3050.1985 - val_loss: 3193.4417
Epoch 43/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2844.6787 - val_loss: 3038.4824
Epoch 44/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3629.1160 - val_loss: 2891.3843
Epoch 45/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3082.8552 - val_loss: 2739.4629
Epoch 46/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2890.4456 - val_loss: 2599.4470
Epoch 47/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2485.1416 - val_loss: 2474.6604
Epoch 48/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2216.7483 - val_loss: 2351.5562
Epoch 49/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2617.4399 - val_loss: 2237.4207
Epoch 50/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2113.0027 - val_loss: 2123.3760
Epoch 51/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1973.1005 - val_loss: 2013.7031
Epoch 52/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1623.2902 - val_loss: 1905.8293
Epoch 53/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2173.2261 - val_loss: 1807.8573
Epoch 54/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1890.2697 - val_loss: 1720.0970
Epoch 55/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1810.8247 - val_loss: 1631.2000
Epoch 56/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1443.0057 - val_loss: 1552.2841
Epoch 57/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1407.0996 - val_loss: 1479.7264
Epoch 58/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1293.5732 - val_loss: 1401.7371
Epoch 59/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1412.7272 - val_loss: 1335.1193
Epoch 60/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1473.5554 - val_loss: 1269.8286
Epoch 61/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1398.4468 - val_loss: 1206.8204
Epoch 62/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1259.1218 - val_loss: 1149.8718
Epoch 63/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1260.7578 - val_loss: 1092.3062
Epoch 64/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1240.6934 - val_loss: 1042.6385
Epoch 65/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1084.4115 - val_loss: 996.7180
Epoch 66/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1074.0315 - val_loss: 952.5052
Epoch 67/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 965.6878 - val_loss: 907.9299
Epoch 68/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 956.6282 - val_loss: 865.1981
Epoch 69/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 678.9459 - val_loss: 830.0547
Epoch 70/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1064.0048 - val_loss: 790.0759
Epoch 71/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 680.2311 - val_loss: 755.7297
Epoch 72/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 667.1332 - val_loss: 723.1360
Epoch 73/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 725.8592 - val_loss: 693.4875
Epoch 74/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 813.3630 - val_loss: 664.9265
Epoch 75/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 539.8015 - val_loss: 635.9688
Epoch 76/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 593.8228 - val_loss: 611.1686
Epoch 77/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 474.4909 - val_loss: 588.3383
Epoch 78/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 506.8835 - val_loss: 564.1190
Epoch 79/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 585.9420 - val_loss: 540.4861
Epoch 80/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 500.9431 - val_loss: 519.3157
Epoch 81/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 545.4583 - val_loss: 499.9435
Epoch 82/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 422.8052 - val_loss: 481.8795
Epoch 83/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 362.4085 - val_loss: 465.5582
Epoch 84/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 506.3884 - val_loss: 448.8801
Epoch 85/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 438.5842 - val_loss: 431.7187
Epoch 86/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 431.8062 - val_loss: 416.0201
Epoch 87/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 352.8057 - val_loss: 402.3222
Epoch 88/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 315.4391 - val_loss: 389.1952
Epoch 89/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 370.8494 - val_loss: 375.8496
Epoch 90/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 356.9180 - val_loss: 363.9169
Epoch 91/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 370.2271 - val_loss: 351.5573
Epoch 92/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 541.8303 - val_loss: 339.9033
Epoch 93/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 344.0919 - val_loss: 329.1044
Epoch 94/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 291.2441 - val_loss: 318.8366
Epoch 95/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 384.2383 - val_loss: 309.7638
Epoch 96/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 247.5369 - val_loss: 300.8159
Epoch 97/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 298.0128 - val_loss: 290.7601
Epoch 98/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 240.8524 - val_loss: 282.5411
Epoch 99/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 233.8316 - val_loss: 274.3564
Epoch 100/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 257.8521 - val_loss: 266.5499

In [ ]:
yp = ann.predict(xtest)
yp

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

array([[475.26416],
       [527.2868 ],
       [495.44736],
       [536.90753],
       [657.6441 ],
       [344.59042],
       [353.5262 ],
       [374.1319 ],
       [722.6486 ],
       [501.4367 ],
       [477.83337],
       [508.04617],
       [495.8791 ],
       [372.79373],
       [549.9001 ],
       [489.6712 ],
       [578.107  ],
       [550.8205 ],
       [482.6478 ],
       [498.7089 ],
       [467.2224 ],
       [603.89746],
       [438.85587],
       [579.9884 ],
       [423.64746],
       [522.5955 ],
       [384.80753],
       [497.71814],
       [544.15515],
       [351.19684],
       [438.10104],
       [642.66583],
       [561.5337 ],
       [538.6183 ],
       [612.2675 ],
       [550.5455 ],
       [405.82   ],
       [575.973  ],
       [557.9389 ],
       [521.0002 ],
       [420.24152],
       [737.71625],
       [525.62744],
       [532.5995 ],
       [515.89685],
       [451.11887],
       [526.7655 ],
       [525.20605],
       [590.4198 ],
       [466.00934],
       [389.03577],
       [632.53   ],
       [814.0358 ],
       [528.59143],
       [651.6547 ],
       [535.3933 ],
       [490.30737],
       [542.6479 ],
       [550.2739 ],
       [373.41965],
       [643.3256 ],
       [467.7058 ],
       [476.55917],
       [506.63705],
       [563.7279 ],
       [345.73013],
       [556.9265 ],
       [546.0818 ],
       [439.2364 ],
       [596.8578 ],
       [559.3251 ],
       [420.5286 ],
       [457.27985],
       [675.75214],
       [400.42957],
       [550.7755 ],
       [335.2218 ],
       [446.6386 ],
       [604.8958 ],
       [538.5617 ],
       [445.28708],
       [438.55673],
       [363.95212],
       [473.57907],
       [395.30298],
       [670.14514],
       [389.88538],
       [554.59467],
       [570.1265 ],
       [368.76065],
       [408.70212],
       [501.00537],
       [551.88513],
       [563.9803 ],
       [733.2733 ],
       [540.4847 ],
       [615.3047 ],
       [623.5848 ],
       [626.1225 ],
       [539.3453 ],
       [495.91864],
       [520.0362 ],
       [582.6144 ],
       [429.25528],
       [613.14075],
       [412.46222],
       [362.3989 ],
       [430.9609 ],
       [409.88654],
       [489.11804],
       [477.69922],
       [406.28235],
       [475.99323],
       [416.45856],
       [332.15817],
       [587.49335],
       [491.56516],
       [397.67346],
       [415.10925],
       [554.4602 ],
       [475.27463],
       [454.44028],
       [537.57416],
       [539.35876],
       [568.4232 ],
       [502.41898],
       [509.95654],
       [392.1336 ],
       [559.7946 ],
       [590.19257],
       [596.66223],
       [434.20114],
       [563.7407 ],
       [387.48596],
       [462.99142],
       [655.67285],
       [618.42725],
       [504.87146],
       [613.68774],
       [605.9431 ],
       [578.4911 ],
       [459.147  ],
       [660.9999 ],
       [361.90414],
       [484.72723],
       [540.6344 ],
       [527.3169 ],
       [579.9858 ],
       [650.92944],
       [492.73114],
       [482.33142],
       [499.03403],
       [358.1519 ],
       [479.7116 ],
       [551.00757],
       [458.49722],
       [604.88556],
       [570.68036],
       [453.1662 ],
       [442.54285],
       [450.11575],
       [529.267  ],
       [394.9382 ],
       [509.17368],
       [465.82034],
       [354.97775],
       [539.9277 ],
       [400.79996],
       [629.252  ],
       [638.6633 ],
       [410.44604],
       [462.08496],
       [494.87488],
       [456.4391 ],
       [399.43723],
       [620.5422 ],
       [522.82025],
       [645.3589 ],
       [341.80817],
       [436.7138 ],
       [459.04877],
       [339.20532],
       [387.26044],
       [541.087  ],
       [503.0614 ],
       [501.55695],
       [476.51196],
       [504.4107 ],
       [513.2829 ],
       [370.35138],
       [434.57166],
       [514.29926],
       [501.86658],
       [550.3599 ],
       [441.18442],
       [450.01547],
       [587.66595],
       [483.61432],
       [503.82202],
       [453.95193]], dtype=float32)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(ytest,yp)

0.9666495459060533